language: ruby
rvm:
  - 1.9.3

install: true
  
addons:
  firefox: "24.0"

before_script:
  - env
  - phantomjs --version
  - ./scripts/run_sc_server_master.sh
  - sleep 5 # give sc-server some time to start

script: phantomjs phantomjs/test_runner.js --no-experimental --exclude-targets=/sproutcore/greenhouse
